version: '3.8'

services:
  mysql-user-service:
    image: mysql:8.0
    container_name: mysql-user-service
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: service_user
      MYSQL_PASSWORD: user_pass
